version: '3'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - postgres
    postgres:
        image: postgres:13
        container_name: db_local
        env_file:
          - .env
        ports:
          - "5432:5432"
        network_mode: host
        logging:
          driver: gelf
          options:
            gelf-address: udp://localhost:12202