version: '3.7'
services:
    back:
        build:
          context: ./backend
          dockerfile: ./Dockerfile
        container_name: back
        ports:
            - "5000:5000"

    postgres:
        image: postgres:13
        container_name: db_local
        env_file:
            - .env
        ports:
            - "5432:5432"

    app:
        build:
          context: ./app/
        command: npm start
        volumes:
          - ./app/:/usr/app
          - /usr/app/node_modules
        depends_on:
          - back
        ports:
          - "3000:3000"







